# Generated by Django 5.1.15 on 2026-09-23 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('XBOX', 'Xbox'), ('PS1', 'PlayStation 1'), ('DREAMCAST', 'Dreamcast')], max_length=20, unique=True)),
                ('cantidad_inicial', models.PositiveIntegerField(default=0)),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=30)),
                ('fecha_alquiler', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('consola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alquileres', to='appReservas.consola')),
            ],
        ),
    ]
