# Generated by Django 5.2.17 on 2026-09-23 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consola',
            old_name='cantidad_disponible',
            new_name='cantidad',
        ),
        migrations.RemoveField(
            model_name='consola',
            name='cantidad_inicial',
        ),
        migrations.RemoveField(
            model_name='consola',
            name='tipo',
        ),
        migrations.AddField(
            model_name='consola',
            name='nombre',
            field=models.CharField(choices=[('Xbox', 'Xbox'), ('Play 1', 'Play 1'), ('Dreamcast', 'Dreamcast')], default=10, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('consola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='appReservas.consola')),
            ],
        ),
        migrations.DeleteModel(
            name='Alquiler',
        ),
    ]
